services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: project-api-dev
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3001:3001"
      - "5555:5555"
      - "5556:5556"
    depends_on:
      db:
        condition: service_healthy
    #environment:
      #NODE_ENV: development
      #DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?schema=public 
    env_file:
      - ./config/.env.local

  db:
    image: postgres:15
    container_name: project-db-dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - project-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - ./config/.env.local

volumes:
  project-db-data:
