name: Build & Deploy Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        run: |
          echo "${{ secrets.CI_REGISTRY_PASSWORD }}" | docker login ghcr.io \
            -u "${{ secrets.CI_REGISTRY_USER }}" \
            --password-stdin

      - name: Build & push image
        run: |
          docker build -t "${{ secrets.IMAGE_NAME }}" .
          docker push "${{ secrets.IMAGE_NAME }}"

  deploy:
    needs: build
    runs-on: [self-hosted, Linux, X64]
    environment: production

    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        run: |
          echo "${{ secrets.CI_REGISTRY_PASSWORD }}" | docker login ghcr.io \
            -u "${{ secrets.CI_REGISTRY_USER }}" \
            --password-stdin

      - name: Pull & deploy
        env:
          IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
          API_URL: ${{ secrets.API_URL }}
          PROD_PORT: ${{ secrets.PROD_PORT }}

          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}

          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
        run: |
          set -e

          docker pull "$IMAGE_NAME"

          docker network create project-network || true

          docker compose -f docker-compose.prod.yml up -d
          docker compose -f docker-compose.prod.yml ps
