name: Deploy Production

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.CI_REGISTRY_USER }}
          password: ${{ secrets.CI_REGISTRY_PASSWORD }}

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.IMAGE_NAME }}

      - name: Install SSH
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Add SSH Key
        run: |
          echo "${{ secrets.SERVER_SSH_PRIVATE_KEY }}" > private_key
          chmod 600 private_key

      - name: Send docker-compose.prod.yml
        run: scp -o StrictHostKeyChecking=no -i private_key docker-compose.prod.yml ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/opt/project-api/docker-compose.prod.yml

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "
            cd /opt/project-api &&
            docker login -u '${{ secrets.CI_REGISTRY_USER }}' -p '${{ secrets.CI_REGISTRY_PASSWORD }}' ghcr.io &&
            docker pull '${{ secrets.IMAGE_NAME }}' &&
            docker network create project-network || true &&
            IMAGE_NAME='${{ secrets.IMAGE_NAME }}' \
            API_URL='${{ secrets.API_URL }}' \
            JWT_SECRET='${{ secrets.JWT_SECRET }}' \
            DB_USER='${{ secrets.DB_USER }}' \
            DB_PASSWORD='${{ secrets.DB_PASSWORD }}' \
            DB_NAME='${{ secrets.DB_NAME }}' \
            PROD_PORT='${{ secrets.PROD_PORT }}' \
            TAG=prod docker compose -f docker-compose.prod.yml up -d
          "
